### PR TITLE
10x increase in send speed and energy growth rate

### PR DESCRIPTION
**Pull request by cha0sg0d**

### CODE REVIEW

**Comment by cha0sg0d** [comment]
TODO still:
- Speed up silver rate
- Create .env variables to determine how much to speed game up by
- Figure out exactly how changing the energy growth rate affects the s-curve function.

**Comment by evanmays** [comment]
Thanks for working on this!! really helps us speed up how much the AI can learn and how fast it can train

Does this change the local deployment addresses of the smart contracts?

**Comment by evanmays** [comment]
never mind, looks like I did prod client not dev client so it was looking for the wrong addresses.

PR works for me

**Comment by cha0sg0d** [comment]
awesome glad it works. Like I said in the TODO message, there's still some improvements but seems like a good start.

**Pull request merged**
